import { withMermaid } from "vitepress-plugin-mermaid";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Canonical domain (not yet deployed — see AGENTS.md's current-status notes). Set here so
// the sitemap and social-preview tags are correct from day one instead of needing a
// find-and-replace once hosting is actually wired up.
const SITE_URL = "https://bulwark.nrl.ai";

// One designed 1200x630 social card per page (not a generic site-wide image), so links shared
// to Slack/Discord/Twitter get a real preview instead of a blank card. Cards are generated by
// `node scripts/generate-og.mjs` and live in public/og/<slug>.png.
//
// The slug is *derived* from the page path rather than listed in a hand-maintained map. The
// map this replaces is precisely how ten articles shipped with no card at all: they were
// added to the sidebar, nobody remembered the map, and because twitter:card is
// summary_large_image site-wide, a page with no og:image renders a *blank* card — strictly
// worse than having no tags. Deriving the slug means a new article is covered the moment its
// card exists, and `generate-og.mjs --check` fails the build if one doesn't.
const OG_FALLBACK = "home";
const OG_SLUG_OVERRIDES: Record<string, string> = { "index.md": "home" };

function ogSlugFor(relativePath: string): string {
  const slug =
    OG_SLUG_OVERRIDES[relativePath] ??
    relativePath.replace(/\.md$/, "").split("/").pop() ??
    OG_FALLBACK;
  // Never point at a card that isn't on disk — an og:image 404 is as bad as none.
  const onDisk = fileURLToPath(
    new URL(`../public/og/${slug}.png`, import.meta.url),
  );
  return existsSync(onDisk) ? slug : OG_FALLBACK;
}

export default withMermaid({
  title: "Bulwark",
  description:
    "A Linux host security scanner with a native CLI and desktop GUI.",
  lang: "en-US",
  cleanUrls: true,
  // Default to light on first visit (no stored preference / no system-preference match yet)
  // — the toggle is still there, this only changes the initial pick.
  appearance: "light",
  sitemap: { hostname: SITE_URL },
  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: "/shield.svg" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "linux security scanner, security hardening, ssh hardening, rootkit detection, " +
          "clamav, security audit tool, cis benchmark, mitre att&ck, lynis alternative, " +
          "rkhunter, file integrity monitoring, sysadmin security, tauri, rust security tool",
      },
    ],
    ["meta", { name: "robots", content: "index, follow" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Bulwark" }],
    [
      "meta",
      {
        property: "og:title",
        content: "Bulwark — Linux Host Security Scanner",
      },
    ],
    [
      "meta",
      {
        property: "og:description",
        content:
          "A Linux host security scanner with a native CLI and desktop GUI. Checks SSH " +
          "hardening, persistence, kernel/sysctl hardening, and rootkit indicators, and " +
          "explains every finding in plain language with a fix.",
      },
    ],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    [
      "meta",
      {
        name: "twitter:title",
        content: "Bulwark — Linux Host Security Scanner",
      },
    ],
    [
      "meta",
      {
        name: "twitter:description",
        content:
          "A Linux host security scanner with a native CLI and desktop GUI.",
      },
    ],
  ],
  transformPageData(pageData) {
    // Per-page canonical + og:url — without this every page's <head> claims the homepage
    // as canonical (the head[] array above is site-wide), which tells search engines to
    // ignore /guide/architecture and /research/lynis-benchmark as duplicates of "/".
    const canonicalUrl = `${SITE_URL}/${pageData.relativePath}`
      .replace(/index\.md$/, "")
      .replace(/\.md$/, "");
    pageData.frontmatter.head ??= [];
    pageData.frontmatter.head.push(
      ["link", { rel: "canonical", href: canonicalUrl }],
      ["meta", { property: "og:url", content: canonicalUrl }],
    );
    // Each article's frontmatter `description` is what a reader actually sees in a shared
    // link. Without this, all 13 articles inherit the site-wide og:description from head[]
    // above and every one of them previews as the same generic blurb about Bulwark.
    const pageDescription =
      pageData.frontmatter.description ?? pageData.description;
    if (pageDescription) {
      const description = String(pageDescription).replace(/\s+/g, " ").trim();
      pageData.frontmatter.head.push(
        ["meta", { property: "og:description", content: description }],
        ["meta", { name: "twitter:description", content: description }],
      );
    }
    if (pageData.title) {
      pageData.frontmatter.head.push(
        ["meta", { property: "og:title", content: pageData.title }],
        ["meta", { name: "twitter:title", content: pageData.title }],
      );
    }

    const imageUrl = `${SITE_URL}/og/${ogSlugFor(pageData.relativePath)}.png`;
    pageData.frontmatter.head.push(
      ["meta", { property: "og:image", content: imageUrl }],
      ["meta", { property: "og:image:width", content: "1200" }],
      ["meta", { property: "og:image:height", content: "630" }],
      ["meta", { name: "twitter:image", content: imageUrl }],
    );
  },

  // Teal palette matching apps/bulwark-app/src/styles.css's tokens (oklch hue ~194, converted
  // to hex since mermaid doesn't understand oklch()). Only governs light mode — the plugin
  // forces mermaid's own built-in dark theme when `.dark` is on <html>, this config has no
  // effect there (a vitepress-plugin-mermaid limitation, not a choice made here).
  mermaid: {
    theme: "base",
    themeVariables: {
      // Archivo, the same face as the rest of the site. This used to be deliberately unset, on
      // the theory that a custom webfont was what threw off mermaid's node box-height math and
      // clipped the bottom line off every multi-line label. That diagnosis was wrong. The
      // culprit is VitePress's `.vp-doc p` line-height leaking into the <p> that mermaid wraps
      // each label in, making every rendered line 4px taller than the box mermaid measured for
      // it — so the overflow scaled with line count and the last line got sliced in half. It's
      // fixed at the root in theme/custom.css, and with it fixed the font is safe to set, so
      // the diagrams no longer sit in Trebuchet MS while the page around them is in Archivo.
      fontFamily: '"Archivo Variable", ui-sans-serif, system-ui, sans-serif',

      primaryColor: "#d5f2f1",
      primaryTextColor: "#081717",
      primaryBorderColor: "#007372",
      lineColor: "#007372",
      secondaryColor: "#fafcfc",
      secondaryBorderColor: "#dae3e3",
      tertiaryColor: "#ffffff",
      tertiaryBorderColor: "#dae3e3",
      textColor: "#081717",
      actorBkg: "#d5f2f1",
      actorBorder: "#007372",
      actorTextColor: "#081717",
      signalColor: "#007372",
      signalTextColor: "#081717",
    },
  },

  themeConfig: {
    logo: "/shield.svg",
    nav: [
      { text: "Download", link: "/download" },
      { text: "Guide", link: "/guide/architecture" },
      { text: "Articles", link: "/articles/ssh-hardening-checklist" },
      { text: "Research", link: "/research/lynis-benchmark" },
      { text: "GitHub", link: "https://github.com/vietanhdev/bulwark" },
    ],
    sidebar: [
      {
        text: "Guide",
        items: [
          { text: "Architecture & design", link: "/guide/architecture" },
          { text: "Contributing", link: "/guide/contributing" },
        ],
      },
      {
        text: "Articles",
        items: [
          {
            text: "SSH hardening checklist",
            link: "/articles/ssh-hardening-checklist",
          },
          {
            text: "How attackers persist on Linux",
            link: "/articles/linux-persistence-techniques",
          },
          {
            text: "Choosing a security scanner",
            link: "/articles/choosing-a-linux-security-scanner",
          },
          {
            text: "sysctl kernel hardening",
            link: "/articles/sysctl-kernel-hardening",
          },
          {
            text: "Sudoers hardening checklist",
            link: "/articles/sudoers-hardening-checklist",
          },
          {
            text: "Is my Linux server hacked?",
            link: "/articles/is-my-linux-server-hacked",
          },
          {
            text: "auditd rules cheat sheet",
            link: "/articles/auditd-rules-cheat-sheet",
          },
          {
            text: "Reading rkhunter/chkrootkit output",
            link: "/articles/rkhunter-chkrootkit-false-positives",
          },
          {
            text: "Does Linux need antivirus?",
            link: "/articles/does-linux-need-antivirus",
          },
          {
            text: "systemd service sandboxing",
            link: "/articles/systemd-service-sandboxing",
          },
          { text: "Bulwark vs. Wazuh", link: "/articles/bulwark-vs-wazuh" },
          {
            text: "Mapping rules to CIS & MITRE ATT&CK",
            link: "/articles/cis-mitre-mapping",
          },
          {
            text: "fail2ban vs. CrowdSec vs. denyhosts",
            link: "/articles/fail2ban-vs-crowdsec-vs-denyhosts",
          },
        ],
      },
      {
        text: "Research",
        items: [
          {
            text: "Bulwark vs. Lynis benchmark",
            link: "/research/lynis-benchmark",
          },
        ],
      },
    ],
    socialLinks: [
      { icon: "github", link: "https://github.com/vietanhdev/bulwark" },
    ],
    search: { provider: "local" },
    footer: {
      message: "Released under the AGPL-3.0-or-later License.",
      copyright: "Bulwark is an open-source project.",
    },
  },
});
