#!/usr/bin/env bash
# Stage the Flathub *submission* tree from the dev Flatpak manifest.
#
# Why this exists rather than a second hand-maintained manifest: Flathub builds
# the app on its own buildbot, from its own repo (flathub/com.vietanhdev.bulwark).
# The dev manifest's `type: dir, path: ../..` source has nothing to point at
# there — the working tree doesn't exist on the builder. So the submitted
# manifest must fetch a specific tagged commit of this repo instead.
#
# Keeping two manifests in sync by hand is how they drift, so this script derives
# the submission manifest from the dev one: everything (build-commands,
# finish-args, SDK extensions) is inherited, and ONLY the source block is
# rewritten. Change the build in one place; both stay correct.
#
# Usage:
#   scripts/flatpak-gen-flathub-manifest.sh [tag]      # default: latest v* tag
#
# Output: build/flathub-submission/ — copy its contents into a checkout of the
# Flathub PR branch. See packaging/README.md "Submitting to Flathub".
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="com.vietanhdev.bulwark"
SRC_DIR="${REPO_ROOT}/packaging/flatpak"
OUT_DIR="${REPO_ROOT}/build/flathub-submission"
GIT_URL="https://github.com/vietanhdev/bulwark.git"

TAG="${1:-$(git -C "${REPO_ROOT}" tag --list 'v*' --sort=-v:refname | head -n1)}"
[[ -n "${TAG}" ]] || { echo "ERROR: no v* tag found and none given" >&2; exit 1; }

git -C "${REPO_ROOT}" rev-parse --verify --quiet "${TAG}^{commit}" >/dev/null \
  || { echo "ERROR: tag ${TAG} not found locally" >&2; exit 1; }

# Resolve to the commit the tag points at. Flathub requires a commit, not just a
# tag: a tag can be moved after review, a commit hash can't. Both are recorded —
# flatpak-builder verifies the tag resolves to exactly this commit.
COMMIT="$(git -C "${REPO_ROOT}" rev-parse "${TAG}^{commit}")"

# The tag must be on the remote, or the buildbot can't fetch it.
if ! git -C "${REPO_ROOT}" ls-remote --tags --exit-code origin "refs/tags/${TAG}" >/dev/null 2>&1; then
  echo "ERROR: tag ${TAG} is not pushed to origin — the Flathub builder can't fetch it." >&2
  echo "       Run: git push origin ${TAG}" >&2
  exit 1
fi

echo ">> staging Flathub submission for ${APP_ID} @ ${TAG} (${COMMIT:0:12})"
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

# Rewrite only the source block: `type: dir / path: ../..` -> git + tag + commit.
# The generated *-sources.json entries are kept verbatim; they travel with the
# submission as sibling files.
python3 - "$@" <<PY
import re, sys, pathlib

src = pathlib.Path("${SRC_DIR}/${APP_ID}.yaml").read_text()

dir_source = re.compile(r"^      - type: dir\n        path: \.\./\.\.\n", re.M)
if not dir_source.search(src):
    sys.exit("ERROR: expected a 'type: dir / path: ../..' source in the dev manifest.\n"
             "The manifest changed shape — update this script rather than hand-editing "
             "the submission manifest.")

replacement = (
    "      # Flathub builds from a tagged commit of the upstream repo, not a local\n"
    "      # tree. Bump both together — flatpak-builder verifies they agree.\n"
    "      - type: git\n"
    "        url: ${GIT_URL}\n"
    "        tag: ${TAG}\n"
    "        commit: ${COMMIT}\n"
)
out = dir_source.sub(replacement, src, count=1)

# The dev-only build instructions at the top describe the local script, which
# isn't how Flathub builds this. Replace with a pointer back to the source repo.
out = re.sub(
    r"\A(#.*\n)+\n",
    "# Flatpak manifest for the Bulwark GUI, as submitted to Flathub.\n"
    "#\n"
    "# GENERATED by scripts/flatpak-gen-flathub-manifest.sh in the upstream repo\n"
    "# (github.com/vietanhdev/bulwark). Do not hand-edit: regenerate it there so the\n"
    "# dev and submission manifests can't drift apart.\n"
    "#\n"
    "# Privileged scans do not work inside the sandbox; see the upstream\n"
    "# packaging/README.md for the reasoning.\n\n",
    out, count=1,
)

pathlib.Path("${OUT_DIR}/${APP_ID}.yaml").write_text(out)
PY

cp "${SRC_DIR}/cargo-sources.json" "${SRC_DIR}/node-sources.json" "${OUT_DIR}/"
cp "${SRC_DIR}/${APP_ID}.desktop" "${SRC_DIR}/${APP_ID}.metainfo.xml" "${OUT_DIR}/"

# shared-modules carries the libappindicator build chain the manifest references by path.
# Without it the submission is a manifest pointing at a file that isn't there, and the
# Flathub buildbot fails on a missing module rather than anything diagnosable. It is a git
# submodule here, so it must be copied explicitly — `git archive` and a plain file copy of
# the packaging dir both skip it.
if [[ ! -f "${SRC_DIR}/shared-modules/libappindicator/libappindicator-gtk3-12.10.json" ]]; then
  echo "ERROR: packaging/flatpak/shared-modules is empty — run: git submodule update --init" >&2
  exit 1
fi
mkdir -p "${OUT_DIR}/shared-modules"
cp -r "${SRC_DIR}/shared-modules/." "${OUT_DIR}/shared-modules/"
# Drop the submodule's own git metadata; the Flathub repo tracks these as plain files
# (or as its own submodule, which the PR description explains).
rm -rf "${OUT_DIR}/shared-modules/.git"

# x86_64 only, deliberately. Flathub BUILDS every arch listed here, so claiming
# aarch64 without having built it once turns an untested target into a failing
# submission. Everything shipped so far (PPA, AUR, COPR, GitHub releases) is
# x86_64; add aarch64 here once an aarch64 build has actually been proven.
cat >"${OUT_DIR}/flathub.json" <<'JSON'
{
  "only-arches": ["x86_64"]
}
JSON

echo
echo ">> staged in ${OUT_DIR}:"
ls -1 "${OUT_DIR}" | sed 's/^/     /'
echo
echo ">> next:"
echo "     1. flatpak run org.flatpak.Builder --lint manifest '${OUT_DIR}/${APP_ID}.yaml'"
echo "     2. build it once from this staged tree to prove the git source resolves"
echo "     3. copy these files into a flathub/flathub checkout on a branch off 'new-pr'"
echo "     4. open the PR against the 'new-pr' base branch (NOT master)"
