#!/usr/bin/env bash
# Stage the Flathub *submission* tree from the dev Flatpak manifest.
#
# Why this exists rather than a second hand-maintained manifest: Flathub builds
# the app on its own buildbot, from its own repo (flathub/com.vietanhdev.bulwark).
# The dev manifest's `type: dir, path: ../..` source has nothing to point at
# there — the working tree doesn't exist on the builder. So the submitted
# manifest must fetch a specific tagged commit of this repo instead.
#
# Keeping two manifests in sync by hand is how they drift, so this script derives
# the submission manifest from the dev one: everything (build-commands,
# finish-args, SDK extensions) is inherited, and ONLY the source block is
# rewritten. Change the build in one place; both stay correct.
#
# Usage:
#   scripts/flatpak-gen-flathub-manifest.sh [tag]      # default: latest v* tag
#
# Output: build/flathub-submission/ — copy its contents into a checkout of the
# Flathub PR branch. See packaging/README.md "Submitting to Flathub".
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="com.vietanhdev.bulwark"
SRC_DIR="${REPO_ROOT}/packaging/flatpak"
OUT_DIR="${REPO_ROOT}/build/flathub-submission"
GIT_URL="https://github.com/vietanhdev/bulwark.git"

TAG="${1:-$(git -C "${REPO_ROOT}" tag --list 'v*' --sort=-v:refname | head -n1)}"
[[ -n "${TAG}" ]] || { echo "ERROR: no v* tag found and none given" >&2; exit 1; }

git -C "${REPO_ROOT}" rev-parse --verify --quiet "${TAG}^{commit}" >/dev/null \
  || { echo "ERROR: tag ${TAG} not found locally" >&2; exit 1; }

# Resolve to the commit the tag points at. Flathub requires a commit, not just a
# tag: a tag can be moved after review, a commit hash can't. Both are recorded —
# flatpak-builder verifies the tag resolves to exactly this commit.
COMMIT="$(git -C "${REPO_ROOT}" rev-parse "${TAG}^{commit}")"

# The tag must be on the remote, or the buildbot can't fetch it.
if ! git -C "${REPO_ROOT}" ls-remote --tags --exit-code origin "refs/tags/${TAG}" >/dev/null 2>&1; then
  echo "ERROR: tag ${TAG} is not pushed to origin — the Flathub builder can't fetch it." >&2
  echo "       Run: git push origin ${TAG}" >&2
  exit 1
fi

echo ">> staging Flathub submission for ${APP_ID} @ ${TAG} (${COMMIT:0:12})"
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

# Rewrite only the source block: `type: dir / path: ../..` -> git + tag + commit.
# The generated *-sources.json entries are kept verbatim; they travel with the
# submission as sibling files.
python3 - "$@" <<PY
import re, sys, pathlib

src = pathlib.Path("${SRC_DIR}/${APP_ID}.yaml").read_text()

dir_source = re.compile(r"^      - type: dir\n        path: \.\./\.\.\n", re.M)
if not dir_source.search(src):
    sys.exit("ERROR: expected a 'type: dir / path: ../..' source in the dev manifest.\n"
             "The manifest changed shape — update this script rather than hand-editing "
             "the submission manifest.")

replacement = (
    "      # Flathub builds from a tagged commit of the upstream repo, not a local\n"
    "      # tree. Bump both together — flatpak-builder verifies they agree.\n"
    "      - type: git\n"
    "        url: ${GIT_URL}\n"
    "        tag: ${TAG}\n"
    "        commit: ${COMMIT}\n"
)
out = dir_source.sub(replacement, src, count=1)

# The dev-only build instructions at the top describe the local script, which
# isn't how Flathub builds this. Replace with a pointer back to the source repo.
out = re.sub(
    r"\A(#.*\n)+\n",
    "# Flatpak manifest for the Bulwark GUI, as submitted to Flathub.\n"
    "#\n"
    "# GENERATED by scripts/flatpak-gen-flathub-manifest.sh in the upstream repo\n"
    "# (github.com/vietanhdev/bulwark). Do not hand-edit: regenerate it there so the\n"
    "# dev and submission manifests can't drift apart.\n"
    "#\n"
    "# Privileged scans do not work inside the sandbox; see the upstream\n"
    "# packaging/README.md for the reasoning.\n\n",
    out, count=1,
)

pathlib.Path("${OUT_DIR}/${APP_ID}.yaml").write_text(out)
PY

cp "${SRC_DIR}/cargo-sources.json" "${SRC_DIR}/node-sources.json" "${OUT_DIR}/"

# The .desktop and metainfo.xml are deliberately NOT copied. The manifest installs them
# with paths relative to the *git source* it checks out (packaging/flatpak/...), so they
# travel with the upstream repo and have no business in the Flathub one. Checked against
# real Tauri submissions — flathub/io.github.CyberTimon.RapidRAW,
# flathub/org.openscopeproject.TrguiNG and flathub/dev.fredol.open-tv all contain only the
# manifest, the generated *-sources.json, flathub.json and .gitmodules.
#
# shared-modules is likewise NOT copied: the Flathub repo takes it as a git submodule, the
# way TrguiNG does. Copying the files would work but diverges from every reviewed example
# and forks a tree upstream maintains. The branch-prep step below adds it properly.

# Both arches, from 0.9.0 on. Flathub BUILDS every arch listed here on its own
# infrastructure, so this list is a promise rather than a preference.
#
# What backs the aarch64 entry: the release pipeline builds, installs and
# launch-tests the aarch64 GUI natively on arm64 runners (release.yml's
# verify-install and verify-gui-launch matrices), and the offline sources this
# submission ships carry the arm64 native bindings that build needs —
# node-sources.json includes @rolldown/binding-linux-arm64-gnu, and the cargo
# sources are arch-neutral.
#
# What does NOT back it, and is worth stating plainly: no aarch64
# `flatpak-builder` run has completed. Flathub builds from these offline sources
# inside the GNOME runtime, which is a different build system from the .deb
# pipeline that was proven. If the aarch64 build fails on Flathub, drop it back
# to x86_64 here rather than leaving a failing arch in the submission.
cat >"${OUT_DIR}/flathub.json" <<'JSON'
{
  "only-arches": ["x86_64", "aarch64"]
}
JSON

echo
echo ">> staged in ${OUT_DIR}:"
ls -1 "${OUT_DIR}" | sed 's/^/     /'
echo
echo ">> next:"
echo "     1. lint:  flatpak run --command=flatpak-builder-lint org.flatpak.Builder \\"
echo "                 manifest '${OUT_DIR}/${APP_ID}.yaml'"
echo "     2. in a fork of flathub/flathub, branch off 'new-pr':"
echo "          git checkout -b ${APP_ID} new-pr"
echo "          cp ${OUT_DIR}/* ."
echo "          git submodule add https://github.com/flathub/shared-modules shared-modules"
echo "        (the manifest references shared-modules/libappindicator/... — the Flathub repo"
echo "         tracks it as a submodule, as flathub/org.openscopeproject.TrguiNG does)"
echo "     3. build once from that tree to prove the git source and submodule resolve"
echo "     4. open the PR against the 'new-pr' base branch (NOT master)"
echo
echo "     Read https://docs.flathub.org/docs/for-app-authors/requirements first."
echo "     The PR description, checklist answers and review replies must be written by a"
echo "     human. packaging/flatpak/flathub-submission-facts.md holds the technical detail"
echo "     to check the manifest against (untracked working notes, kept out of git so"
echo "     nobody pastes them into a PR whose words have to be their own)."
